name: Doxygen

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "doxygen"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5.0.0

      - name: Install Doxygen
        run: sudo apt-get install doxygen
      
      - name: Generate documentation
        run: doxygen

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: "html"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
